### PR TITLE
SSR Support: delete substate.error property (Next.js getServerSideProps)

### PR DESCRIPTION
**Pull request by gfortaine**
Addresses points brought up in https://github.com/rtk-incubator/rtk-query/issues/88#issuecomment-762288424.

### CODE REVIEW

**Comment by phryneas** [comment]
Hmm. I'm honestly flabbergasted by the stuff next.js is pulling there, but oh well.

I'd suggest we do `delete substate.error` here though - not unsetting it at all would lead to pretty weird behaviour in some situations.

**Comment by msutkowski** [comment]
How does everyone feel about just defaulting to `null` instead of `undefined`? Is that a better long-term solution for this?

**Comment by phryneas** [comment]
Well, it could also just not be present yet or have never been set. And I kinda don't see the point of setting a property to null when it has never been accessed yet - especially since we would have to do that to others then as well consequently.
So I'd rather just use `delete X` instead of `X = undefined`.

**Comment by gfortaine** [comment]
@phryneas PR updated with `delete substate.error` as suggested 👍

**Review by msutkowski — APPROVED** [review]

**Comment by msutkowski** [comment]
Thanks again for this @gfortaine! 🎉

**Pull request merged**
