### PR TITLE
Support a meta property on baseQuery, enhance fetchBaseQuery to pass through Request/Response clones

### LINKED ISSUE #194: Would be great if there was a possibility to access the response headers

### PR DESCRIPTION
**Pull request by msutkowski**
Closes #194 

**Overview**
This PR allows a baseQueryFn to return a `meta` property that will pass through to `transformResponse`, `onSuccess`, and `onError`. `fetchBaseQuery` has been modified to pass through clones of the Request/Response.

**Possible use cases**
- A user could merge the `Response` headers into the result payload
- A user _could_ pass-through properties from the `Request` and/or `Response` to an analytics or logging service in `onError`/`onSuccess`

### CODE REVIEW

**Comment by phryneas** [comment]
added a bit stuff on top of this :)

**Comment by phryneas** [comment]
We should probably merge https://github.com/rtk-incubator/rtk-query/pull/158 before this, since that deduplicates the query & mutation thunk logic.

**Comment by msutkowski** [comment]
@phryneas Looks like I didn't break anything with the merge 🎉. Please just give it a once over :)

**Comment by phryneas** [comment]
Let's get this merged :)

**Pull request merged**
